import { configureStore } from "@reduxjs/toolkit"; // configureStore sets up the store with good defaults (thunk, devtools, etc.)
import weatherReducer from "./weatherSlice"; // the reducer function generated by our weather slice

// The single, app-wide Redux store. Every piece of shared state
// (currently just "weather") is registered here as its own slice.
export const store = configureStore({
  reducer: {
    weather: weatherReducer, // state.weather will hold { current, forecast, loading, error }
  },
});

// RootState is inferred from the store itself, so it always matches
// the real shape of state — no need to hand-write it and let it drift.
export type RootState = ReturnType<typeof store.getState>;

// AppDispatch includes thunk typing, which lets us dispatch async
// thunks (like fetchWeatherByCity) with correct TypeScript types.
export type AppDispatch = typeof store.dispatch;
